// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/role/type/role.proto

package role

import (
	common "github.com/Ilhamkawe/commerce-proto/protogen/go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,18,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,19,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"`
	DeletedBy     string                 `protobuf:"bytes,21,opt,name=deletedBy,proto3" json:"deletedBy,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,22,opt,name=isDeleted,proto3" json:"isDeleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_proto_role_type_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_type_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_proto_role_type_role_proto_rawDescGZIP(), []int{0}
}

func (x *Role) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Role) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Role) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Role) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Role) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Role) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Role) GetDeletedBy() string {
	if x != nil {
		return x.DeletedBy
	}
	return ""
}

func (x *Role) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type RoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.BaseResponse   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Data          *Role                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleResponse) Reset() {
	*x = RoleResponse{}
	mi := &file_proto_role_type_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleResponse) ProtoMessage() {}

func (x *RoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_type_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleResponse.ProtoReflect.Descriptor instead.
func (*RoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_role_type_role_proto_rawDescGZIP(), []int{1}
}

func (x *RoleResponse) GetMeta() *common.BaseResponse {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *RoleResponse) GetData() *Role {
	if x != nil {
		return x.Data
	}
	return nil
}

type IDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDRequest) Reset() {
	*x = IDRequest{}
	mi := &file_proto_role_type_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDRequest) ProtoMessage() {}

func (x *IDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_type_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDRequest.ProtoReflect.Descriptor instead.
func (*IDRequest) Descriptor() ([]byte, []int) {
	return file_proto_role_type_role_proto_rawDescGZIP(), []int{2}
}

func (x *IDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRequest) Reset() {
	*x = SaveRequest{}
	mi := &file_proto_role_type_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRequest) ProtoMessage() {}

func (x *SaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_type_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRequest.ProtoReflect.Descriptor instead.
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return file_proto_role_type_role_proto_rawDescGZIP(), []int{3}
}

func (x *SaveRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SaveRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type BooleanData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BooleanData) Reset() {
	*x = BooleanData{}
	mi := &file_proto_role_type_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BooleanData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooleanData) ProtoMessage() {}

func (x *BooleanData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_type_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooleanData.ProtoReflect.Descriptor instead.
func (*BooleanData) Descriptor() ([]byte, []int) {
	return file_proto_role_type_role_proto_rawDescGZIP(), []int{4}
}

func (x *BooleanData) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *BooleanData) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BooleanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.BaseResponse   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Data          *BooleanData           `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BooleanResponse) Reset() {
	*x = BooleanResponse{}
	mi := &file_proto_role_type_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BooleanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooleanResponse) ProtoMessage() {}

func (x *BooleanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_type_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooleanResponse.ProtoReflect.Descriptor instead.
func (*BooleanResponse) Descriptor() ([]byte, []int) {
	return file_proto_role_type_role_proto_rawDescGZIP(), []int{5}
}

func (x *BooleanResponse) GetMeta() *common.BaseResponse {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *BooleanResponse) GetData() *BooleanData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_role_type_role_proto protoreflect.FileDescriptor

const file_proto_role_type_role_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/role/type/role.proto\x12\x04role\x1a\x1fgoogle/protobuf/timestamp.proto\x1a proto/common/base_response.proto\"\xe4\x02\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x128\n" +
	"\tcreatedAt\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1c\n" +
	"\tcreatedBy\x18\x12 \x01(\tR\tcreatedBy\x12\x1c\n" +
	"\tupdatedBy\x18\x13 \x01(\tR\tupdatedBy\x128\n" +
	"\tdeletedAt\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x1c\n" +
	"\tdeletedBy\x18\x15 \x01(\tR\tdeletedBy\x12\x1c\n" +
	"\tisDeleted\x18\x16 \x01(\bR\tisDeleted\"X\n" +
	"\fRoleResponse\x12(\n" +
	"\x04meta\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04meta\x12\x1e\n" +
	"\x04data\x18\x02 \x01(\v2\n" +
	".role.RoleR\x04data\"\x1b\n" +
	"\tIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"E\n" +
	"\vSaveRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"?\n" +
	"\vBooleanData\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"b\n" +
	"\x0fBooleanResponse\x12(\n" +
	"\x04meta\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04meta\x12%\n" +
	"\x04data\x18\x02 \x01(\v2\x11.role.BooleanDataR\x04dataB6Z4github.com/Ilhamkawe/commerce-proto/protogen/go/roleb\x06proto3"

var (
	file_proto_role_type_role_proto_rawDescOnce sync.Once
	file_proto_role_type_role_proto_rawDescData []byte
)

func file_proto_role_type_role_proto_rawDescGZIP() []byte {
	file_proto_role_type_role_proto_rawDescOnce.Do(func() {
		file_proto_role_type_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_role_type_role_proto_rawDesc), len(file_proto_role_type_role_proto_rawDesc)))
	})
	return file_proto_role_type_role_proto_rawDescData
}

var file_proto_role_type_role_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_role_type_role_proto_goTypes = []any{
	(*Role)(nil),                  // 0: role.Role
	(*RoleResponse)(nil),          // 1: role.RoleResponse
	(*IDRequest)(nil),             // 2: role.IDRequest
	(*SaveRequest)(nil),           // 3: role.SaveRequest
	(*BooleanData)(nil),           // 4: role.BooleanData
	(*BooleanResponse)(nil),       // 5: role.BooleanResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*common.BaseResponse)(nil),   // 7: common.BaseResponse
}
var file_proto_role_type_role_proto_depIdxs = []int32{
	6, // 0: role.Role.createdAt:type_name -> google.protobuf.Timestamp
	6, // 1: role.Role.updatedAt:type_name -> google.protobuf.Timestamp
	6, // 2: role.Role.deletedAt:type_name -> google.protobuf.Timestamp
	7, // 3: role.RoleResponse.meta:type_name -> common.BaseResponse
	0, // 4: role.RoleResponse.data:type_name -> role.Role
	7, // 5: role.BooleanResponse.meta:type_name -> common.BaseResponse
	4, // 6: role.BooleanResponse.data:type_name -> role.BooleanData
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_role_type_role_proto_init() }
func file_proto_role_type_role_proto_init() {
	if File_proto_role_type_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_role_type_role_proto_rawDesc), len(file_proto_role_type_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_role_type_role_proto_goTypes,
		DependencyIndexes: file_proto_role_type_role_proto_depIdxs,
		MessageInfos:      file_proto_role_type_role_proto_msgTypes,
	}.Build()
	File_proto_role_type_role_proto = out.File
	file_proto_role_type_role_proto_goTypes = nil
	file_proto_role_type_role_proto_depIdxs = nil
}
