// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/role/service.proto

package role

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_role_service_proto protoreflect.FileDescriptor

const file_proto_role_service_proto_rawDesc = "" +
	"\n" +
	"\x18proto/role/service.proto\x12\x04role\x1a\x1aproto/role/type/role.proto2\xa1\x01\n" +
	"\vRoleService\x12-\n" +
	"\x04Save\x12\x11.role.SaveRequest\x1a\x12.role.RoleResponse\x120\n" +
	"\x06Delete\x12\x0f.role.IDRequest\x1a\x15.role.BooleanResponse\x121\n" +
	"\aDestroy\x12\x0f.role.IDRequest\x1a\x15.role.BooleanResponseB6Z4github.com/Ilhamkawe/commerce-proto/protogen/go/roleb\x06proto3"

var file_proto_role_service_proto_goTypes = []any{
	(*SaveRequest)(nil),     // 0: role.SaveRequest
	(*IDRequest)(nil),       // 1: role.IDRequest
	(*RoleResponse)(nil),    // 2: role.RoleResponse
	(*BooleanResponse)(nil), // 3: role.BooleanResponse
}
var file_proto_role_service_proto_depIdxs = []int32{
	0, // 0: role.RoleService.Save:input_type -> role.SaveRequest
	1, // 1: role.RoleService.Delete:input_type -> role.IDRequest
	1, // 2: role.RoleService.Destroy:input_type -> role.IDRequest
	2, // 3: role.RoleService.Save:output_type -> role.RoleResponse
	3, // 4: role.RoleService.Delete:output_type -> role.BooleanResponse
	3, // 5: role.RoleService.Destroy:output_type -> role.BooleanResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_role_service_proto_init() }
func file_proto_role_service_proto_init() {
	if File_proto_role_service_proto != nil {
		return
	}
	file_proto_role_type_role_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_role_service_proto_rawDesc), len(file_proto_role_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_role_service_proto_goTypes,
		DependencyIndexes: file_proto_role_service_proto_depIdxs,
	}.Build()
	File_proto_role_service_proto = out.File
	file_proto_role_service_proto_goTypes = nil
	file_proto_role_service_proto_depIdxs = nil
}
