// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/user/service.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_user_service_proto protoreflect.FileDescriptor

const file_proto_user_service_proto_rawDesc = "" +
	"\n" +
	"\x18proto/user/service.proto\x12\x04user\x1a\x1aproto/user/type/user.proto\x1a\x1bgoogle/protobuf/empty.proto2\xf1\x01\n" +
	"\vUserService\x128\n" +
	"\bRegister\x12\x15.user.RegisterRequest\x1a\x15.user.BooleanResponse\x120\n" +
	"\x05Login\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponse\x12=\n" +
	"\rGetUserDetail\x12\x16.google.protobuf.Empty\x1a\x14.user.DetailResponse\x127\n" +
	"\x06Logout\x12\x16.google.protobuf.Empty\x1a\x15.user.BooleanResponseB6Z4github.com/Ilhamkawe/commerce-proto/protogen/go/userb\x06proto3"

var file_proto_user_service_proto_goTypes = []any{
	(*RegisterRequest)(nil), // 0: user.RegisterRequest
	(*LoginRequest)(nil),    // 1: user.LoginRequest
	(*emptypb.Empty)(nil),   // 2: google.protobuf.Empty
	(*BooleanResponse)(nil), // 3: user.BooleanResponse
	(*LoginResponse)(nil),   // 4: user.LoginResponse
	(*DetailResponse)(nil),  // 5: user.DetailResponse
}
var file_proto_user_service_proto_depIdxs = []int32{
	0, // 0: user.UserService.Register:input_type -> user.RegisterRequest
	1, // 1: user.UserService.Login:input_type -> user.LoginRequest
	2, // 2: user.UserService.GetUserDetail:input_type -> google.protobuf.Empty
	2, // 3: user.UserService.Logout:input_type -> google.protobuf.Empty
	3, // 4: user.UserService.Register:output_type -> user.BooleanResponse
	4, // 5: user.UserService.Login:output_type -> user.LoginResponse
	5, // 6: user.UserService.GetUserDetail:output_type -> user.DetailResponse
	3, // 7: user.UserService.Logout:output_type -> user.BooleanResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_user_service_proto_init() }
func file_proto_user_service_proto_init() {
	if File_proto_user_service_proto != nil {
		return
	}
	file_proto_user_type_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_service_proto_rawDesc), len(file_proto_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_service_proto_goTypes,
		DependencyIndexes: file_proto_user_service_proto_depIdxs,
	}.Build()
	File_proto_user_service_proto = out.File
	file_proto_user_service_proto_goTypes = nil
	file_proto_user_service_proto_depIdxs = nil
}
