// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/user/type/user.proto

package user

import (
	common "github.com/Ilhamkawe/commerce-proto/protogen/go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	RoleCode      string                 `protobuf:"bytes,6,opt,name=role_code,json=roleCode,proto3" json:"role_code,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,17,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,18,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"`
	DeletedBy     string                 `protobuf:"bytes,20,opt,name=deletedBy,proto3" json:"deletedBy,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,21,opt,name=isDeleted,proto3" json:"isDeleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_user_type_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_type_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_user_type_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *User) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *User) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *User) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *User) GetDeletedBy() string {
	if x != nil {
		return x.DeletedBy
	}
	return ""
}

func (x *User) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type RegisterRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FullName       string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password       string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	RepeatPassword string                 `protobuf:"bytes,5,opt,name=repeatPassword,proto3" json:"repeatPassword,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_user_type_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_type_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_type_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetRepeatPassword() string {
	if x != nil {
		return x.RepeatPassword
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_user_type_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_type_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_type_user_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	RoleCode      string                 `protobuf:"bytes,3,opt,name=role_code,json=roleCode,proto3" json:"role_code,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginData) Reset() {
	*x = LoginData{}
	mi := &file_proto_user_type_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginData) ProtoMessage() {}

func (x *LoginData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_type_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginData.ProtoReflect.Descriptor instead.
func (*LoginData) Descriptor() ([]byte, []int) {
	return file_proto_user_type_user_proto_rawDescGZIP(), []int{3}
}

func (x *LoginData) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *LoginData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginData) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

func (x *LoginData) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.BaseResponse   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Data          *LoginData             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_user_type_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_type_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_type_user_proto_rawDescGZIP(), []int{4}
}

func (x *LoginResponse) GetMeta() *common.BaseResponse {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *LoginResponse) GetData() *LoginData {
	if x != nil {
		return x.Data
	}
	return nil
}

type BooleanData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BooleanData) Reset() {
	*x = BooleanData{}
	mi := &file_proto_user_type_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BooleanData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooleanData) ProtoMessage() {}

func (x *BooleanData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_type_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooleanData.ProtoReflect.Descriptor instead.
func (*BooleanData) Descriptor() ([]byte, []int) {
	return file_proto_user_type_user_proto_rawDescGZIP(), []int{5}
}

func (x *BooleanData) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *BooleanData) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BooleanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.BaseResponse   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Data          *BooleanData           `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BooleanResponse) Reset() {
	*x = BooleanResponse{}
	mi := &file_proto_user_type_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BooleanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooleanResponse) ProtoMessage() {}

func (x *BooleanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_type_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooleanResponse.ProtoReflect.Descriptor instead.
func (*BooleanResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_type_user_proto_rawDescGZIP(), []int{6}
}

func (x *BooleanResponse) GetMeta() *common.BaseResponse {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *BooleanResponse) GetData() *BooleanData {
	if x != nil {
		return x.Data
	}
	return nil
}

type DetailData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	RoleCode      string                 `protobuf:"bytes,4,opt,name=role_code,json=roleCode,proto3" json:"role_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailData) Reset() {
	*x = DetailData{}
	mi := &file_proto_user_type_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailData) ProtoMessage() {}

func (x *DetailData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_type_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailData.ProtoReflect.Descriptor instead.
func (*DetailData) Descriptor() ([]byte, []int) {
	return file_proto_user_type_user_proto_rawDescGZIP(), []int{7}
}

func (x *DetailData) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *DetailData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DetailData) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DetailData) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

type DetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.BaseResponse   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Data          *DetailData            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailResponse) Reset() {
	*x = DetailResponse{}
	mi := &file_proto_user_type_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailResponse) ProtoMessage() {}

func (x *DetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_type_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailResponse.ProtoReflect.Descriptor instead.
func (*DetailResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_type_user_proto_rawDescGZIP(), []int{8}
}

func (x *DetailResponse) GetMeta() *common.BaseResponse {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *DetailResponse) GetData() *DetailData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_user_type_user_proto protoreflect.FileDescriptor

const file_proto_user_type_user_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/user/type/user.proto\x12\x04user\x1a\x1fgoogle/protobuf/timestamp.proto\x1a proto/common/base_response.proto\"\xbb\x03\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bfullName\x18\x03 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x1b\n" +
	"\trole_code\x18\x06 \x01(\tR\broleCode\x128\n" +
	"\tcreatedAt\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1c\n" +
	"\tcreatedBy\x18\x11 \x01(\tR\tcreatedBy\x12\x1c\n" +
	"\tupdatedBy\x18\x12 \x01(\tR\tupdatedBy\x128\n" +
	"\tdeletedAt\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x1c\n" +
	"\tdeletedBy\x18\x14 \x01(\tR\tdeletedBy\x12\x1c\n" +
	"\tisDeleted\x18\x15 \x01(\bR\tisDeleted\"\x88\x01\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12&\n" +
	"\x0erepeatPassword\x18\x05 \x01(\tR\x0erepeatPassword\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"p\n" +
	"\tLoginData\x12\x1a\n" +
	"\bfullName\x18\x01 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1b\n" +
	"\trole_code\x18\x03 \x01(\tR\broleCode\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"^\n" +
	"\rLoginResponse\x12(\n" +
	"\x04meta\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04meta\x12#\n" +
	"\x04data\x18\x02 \x01(\v2\x0f.user.LoginDataR\x04data\"?\n" +
	"\vBooleanData\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"b\n" +
	"\x0fBooleanResponse\x12(\n" +
	"\x04meta\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04meta\x12%\n" +
	"\x04data\x18\x02 \x01(\v2\x11.user.BooleanDataR\x04data\"w\n" +
	"\n" +
	"DetailData\x12\x1a\n" +
	"\bfullName\x18\x01 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1b\n" +
	"\trole_code\x18\x04 \x01(\tR\broleCode\"`\n" +
	"\x0eDetailResponse\x12(\n" +
	"\x04meta\x18\x01 \x01(\v2\x14.common.BaseResponseR\x04meta\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.user.DetailDataR\x04dataB6Z4github.com/Ilhamkawe/commerce-proto/protogen/go/userb\x06proto3"

var (
	file_proto_user_type_user_proto_rawDescOnce sync.Once
	file_proto_user_type_user_proto_rawDescData []byte
)

func file_proto_user_type_user_proto_rawDescGZIP() []byte {
	file_proto_user_type_user_proto_rawDescOnce.Do(func() {
		file_proto_user_type_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_type_user_proto_rawDesc), len(file_proto_user_type_user_proto_rawDesc)))
	})
	return file_proto_user_type_user_proto_rawDescData
}

var file_proto_user_type_user_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_user_type_user_proto_goTypes = []any{
	(*User)(nil),                  // 0: user.User
	(*RegisterRequest)(nil),       // 1: user.RegisterRequest
	(*LoginRequest)(nil),          // 2: user.LoginRequest
	(*LoginData)(nil),             // 3: user.LoginData
	(*LoginResponse)(nil),         // 4: user.LoginResponse
	(*BooleanData)(nil),           // 5: user.BooleanData
	(*BooleanResponse)(nil),       // 6: user.BooleanResponse
	(*DetailData)(nil),            // 7: user.DetailData
	(*DetailResponse)(nil),        // 8: user.DetailResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*common.BaseResponse)(nil),   // 10: common.BaseResponse
}
var file_proto_user_type_user_proto_depIdxs = []int32{
	9,  // 0: user.User.createdAt:type_name -> google.protobuf.Timestamp
	9,  // 1: user.User.updatedAt:type_name -> google.protobuf.Timestamp
	9,  // 2: user.User.deletedAt:type_name -> google.protobuf.Timestamp
	10, // 3: user.LoginResponse.meta:type_name -> common.BaseResponse
	3,  // 4: user.LoginResponse.data:type_name -> user.LoginData
	10, // 5: user.BooleanResponse.meta:type_name -> common.BaseResponse
	5,  // 6: user.BooleanResponse.data:type_name -> user.BooleanData
	10, // 7: user.DetailResponse.meta:type_name -> common.BaseResponse
	7,  // 8: user.DetailResponse.data:type_name -> user.DetailData
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_user_type_user_proto_init() }
func file_proto_user_type_user_proto_init() {
	if File_proto_user_type_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_type_user_proto_rawDesc), len(file_proto_user_type_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_user_type_user_proto_goTypes,
		DependencyIndexes: file_proto_user_type_user_proto_depIdxs,
		MessageInfos:      file_proto_user_type_user_proto_msgTypes,
	}.Build()
	File_proto_user_type_user_proto = out.File
	file_proto_user_type_user_proto_goTypes = nil
	file_proto_user_type_user_proto_depIdxs = nil
}
